Integration branch
camilaF2022/Catalogo pull request #9
Opened 2024-05-27 05:43 UTC by lukasvaz

Integration front -back
App  look like this 
![Grabación-de-pantalla-desde-26-05-24-22_31_12](https://github.com/camilaF2022/Catalogo/assets/84355843/2767e37b-9860-4f21-ad0b-006732f376fe)

## General changes 
- refactoring  views  in backend  to  match {status:"succes", data:{}}  format
-  refactoring  serializers  to get absolute path (localhost:8000/)  for media files
- import3D does not move files , importDescription  works  with the format given in the  drive
- changing  endpoints in frontend  to fetch data  from  backend
- refactoring  components in frontend  to  fetch (id,value )  format
- Read me  with general  instructions to launch backend

##Important changes in Frontend 
- refactoring project structure  to  
     /frontend/->(public/ src/  ....)

## Important Changes Backend 
 - remove  migrations files to avoid migration error.
 - all data uploaded to backend (models or images) will  be uploaded to /media folder , after running commands  /media should have  /images /materials /objects /thumbnails  folder
 - gitignoring  db.sqlite  to prevent discrepancies
 
# Important TODOs in backend 
-   unifyi command inputs  to make  uploads easier (avoid the multimedia folder for images)
- thumbs are duplicated once running the command, should be unique
- artifacts are  loaded  depending on  whether they  have description or not  (100 artifacts), should be independent

2024-05-29 00:02 UTC, lukasvaz commented
'succes' typo fixed , and  deleting  CustomStorage() functionality (not necessary).

2024-05-31 03:47 UTC, lukasvaz commented
- merging   from HomepageFront

2024-05-31 18:51 UTC, IsaiasVenegas commented on README.md
>  npm start
To rewrite

2024-05-31 18:52 UTC, IsaiasVenegas commented on backend/catalogo_arqueologico/catalogo_arqueologico/serializer.py
> +    nombre_completo = serializers.SerializerMethodField()
Rename this

2024-05-31 18:54 UTC, IsaiasVenegas commented on backend/catalogo_arqueologico/piezas/management/commands/importCulture.py
>                      print("Error: No se puede insertar un objeto con el mismo valor para 'nombre'.")
Use logger instead of print function

2024-05-31 18:54 UTC, IsaiasVenegas commented on backend/catalogo_arqueologico/piezas/management/commands/importCulture.py
> +                print("todo funciona bien")
Delete this print

2024-05-31 18:55 UTC, IsaiasVenegas commented on backend/catalogo_arqueologico/piezas/management/commands/importDescriptions.py
> +                print(realId)
Delete this print

2024-05-31 18:55 UTC, IsaiasVenegas commented on backend/catalogo_arqueologico/piezas/management/commands/importDescriptions.py
> +                print("se guardo un artefacto")
Delete this print

2024-05-31 18:55 UTC, IsaiasVenegas commented on backend/catalogo_arqueologico/piezas/management/commands/importImage.py
> +        print(image_files)
Delete this print

2024-05-31 18:56 UTC, IsaiasVenegas commented on backend/catalogo_arqueologico/piezas/management/commands/importShape.py
> +                    print("Error: No se puede insertar un objeto con el mismo valor para 'nombre'.")
Use logger instead of print function

2024-05-31 18:56 UTC, IsaiasVenegas commented on backend/catalogo_arqueologico/piezas/management/commands/importShape.py
> +                print("No se encontro el txt")
Same here

2024-05-31 18:57 UTC, IsaiasVenegas commented on backend/catalogo_arqueologico/piezas/management/commands/importTags.py
>                          print("Error: No se puede insertar un objeto con el mismo valor para 'nombre'.")
Same here

2024-05-31 18:57 UTC, IsaiasVenegas commented on backend/catalogo_arqueologico/piezas/management/commands/importThumbs.py
> +        print(thumb_files)
Delete this print

2024-05-31 18:57 UTC, IsaiasVenegas commented on backend/catalogo_arqueologico/piezas/management/commands/importThumbs.py
> +                print(thumbnail)
Delete this print

2024-05-31 18:57 UTC, IsaiasVenegas commented on backend/catalogo_arqueologico/piezas/management/commands/importTags.py
> +                    print("aqui sigue")
Delete this print

2024-05-31 19:04 UTC, IsaiasVenegas commented on backend/catalogo_arqueologico/piezas/models.py
Import route for "upload_to" as constant from settings

2024-05-31 19:04 UTC, IsaiasVenegas commented on backend/catalogo_arqueologico/piezas/models.py
> +    path = models.ImageField(upload_to='images/',unique=True)
Import route for "upload_to" as constant from settings

2024-05-31 20:02 UTC, IsaiasVenegas requested changes

2024-05-31 20:02 UTC, IsaiasVenegas commented on frontend/src/pages/Gallery/Gallery.jsx
> +    fetch("http://localhost:8000/piezas/catalog/")
Define endpoints in a diferent file

2024-05-31 20:02 UTC, IsaiasVenegas commented on frontend/src/pages/Gallery/components/CustomFilter.jsx
> +    fetch("/pieces_models/response.json")
Define endpoints in a diferent file

2024-05-31 20:02 UTC, IsaiasVenegas commented on frontend/src/pages/ObjectDetail/ObjectDetail.jsx
> +      .then((response) => {
Define endpoints in a diferent file

2024-05-31 20:02 UTC, IsaiasVenegas commented on frontend/src/pages/ObjectDetail/components/DownloadForm.jsx
> +  }
Delete element after download

2024-06-03 20:45 UTC, merged